### ISSUE TITLE
Simplify query dsl

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/karp-backend#129]
- [x] Allow all query expressions
- [x] Combine arbitrary queries with `and`, e.g. `and||<query1>||<query2>||...||<queryN>`
- [x] Combine arbitrary queries with `or`, e.g. `or||<query1>||<query2>||...||<queryN>`
- [ ] Combine arbitrary queries with `not`, e.g. `not||<query1>||<query2>||...||<queryN>`
- [ ] Use more than one logical operator. How shall this work?
- [ ] `and||<query1>||or||<query2>||<query3>`
- [ ] Maybe allow: `or||and||<query1>||<query2>||and||<query3>||<query4|` =>
```
or(
  and(
    query1,
    query2,
    and(
      query3,
      query4
    )
  )
)
```

**Comment by majsan** [comment]
Done
