### ISSUE TITLE
Create an autocomplete call for Korp

### ISSUE THREAD

**Issue by majsan** [spraakbanken/karp-backend#245]
The Korp frontend uses an old Karp API to lookup word forms and get lemgrams containing the word forms, for example:

https://ws.spraakbanken.gu.se/ws/karp/v4/autocomplete?mode=external&q=h%C3%A4st&resource=saldom

https://ws.spraakbanken.gu.se/ws/karp/v4/autocomplete?mode=external&q=hu&resource=swedbergm,dalinm,saldom,fsvm

If the user searches for "häst", lemgrams with a wordform "till häst" should still be returned, so we have to search in a tokenized field. It is important that Korp does not have to fetch entire entries each time a call is made. So a query for `häst` should ideally give back just `["häst..nn.1", "till_häst..abm.1", ...]` and nothing else.

What to do:
- create resources `saldom` (done), `swedbergm` (ignore if empty), `dalim`, `fsvm`. The inflection table should use an analyzer with lowercase and tokenization in Elasticsearch.
- Find the correct query to give the desired results. They should be sorted on relevance
- Either create a new call which only returns a list of lemgrams OR add a new parameter to the query-call where the caller can filter out the needed data using for example `jq`.
- Ask the Korp team to use the new API

**Comment by nick8325** [comment]
In `plugin.py` there's a function which can look up a field (also nested ones) in a JSON object. Maybe we could use that for returning the lemgram (and move it out into its own file)?

**Comment by nick8325** [comment]
(Now there is `karp.foundation.json` with a `get_path` function.)
