### ISSUE TITLE
Resource dependency issues

### ISSUE THREAD

**Issue by majsan** [spraakbanken/karp-backend#273]
If resource A depends on resource B via the link-plugin, resource B must be created before A, otherwise we get the cryptic error:

AttributeError: 'list' object has no attribute 'items' (in `karp.plugins.plugin._transform_fields`)

Fix a better error message like: "Resource A depends on resource B, create resource B first".

**Comment by nick8325** [comment]
The crash was caused by a bug in link_plugin :)

Now the behaviour is that the resource is created, but the virtual field will not appear in resource A until you run a `karp-cli resource reindex`. (I guess it would still be good to get a warning?)
