### ISSUE TITLE
Upgrade pydantic, FastAPI and uvicorn

### ISSUE THREAD

**Issue by majsan** [spraakbanken/karp-backend#274]
Latest versions did not work out of the box.

Latest uvicorn worked locally, but not on server, which might be due to the server using `--root-path`.

**Comment by nick8325** [comment]
Pydantic has quite a lot of breaking changes which might be why it didn't work, see https://docs.pydantic.dev/latest/migration/. For example some methods changed name and the way to configure the model config changed.

**Comment by nick8325** [comment]
I've upgraded FastAPI and pydantic now

**Comment by majsan** [comment]
@nick8325 Generating the documentation does not work now due to errors in unique_id.py:

```
  File "/home/maria/språkbanken/karp/karp-backend/karp/foundation/value_objects/unique_id.py", line 13, in __get_pydantic_json_schema__
    json_schema = handler(core_schema.str_schema())
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'str_schema
```

I am trying to fix it, but maybe you have a better idea what's wrong.

**Comment by nick8325** [comment]
Think I just wrote something stupid :) I can try and fix it.

**Comment by nick8325** [comment]
Done! I think it was a search and replace that went wrong.

**Comment by nick8325** [comment]
(re-opening because there is still uvicorn to be done, right?)

**Comment by majsan** [comment]
I opened a new one #276, so we can close this.
